apiVersion: v1
kind: Service
metadata:
  name:
  labels:
    app:
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  labels:
    app: basic-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-app
        image: 35.242.144.237:5000/basic_app:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
          path: /
          port: 5000

